/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as WhatifRouteImport } from './routes/whatif'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as ModelRouteImport } from './routes/model'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as ExplainabilityRouteImport } from './routes/explainability'
import { Route as CompsRouteImport } from './routes/comps'
import { Route as IndexRouteImport } from './routes/index'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatifRoute = WhatifRouteImport.update({
  id: '/whatif',
  path: '/whatif',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelRoute = ModelRouteImport.update({
  id: '/model',
  path: '/model',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplainabilityRoute = ExplainabilityRouteImport.update({
  id: '/explainability',
  path: '/explainability',
  getParentRoute: () => rootRouteImport,
} as any)
const CompsRoute = CompsRouteImport.update({
  id: '/comps',
  path: '/comps',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/comps': typeof CompsRoute
  '/explainability': typeof ExplainabilityRoute
  '/feedback': typeof FeedbackRoute
  '/model': typeof ModelRoute
  '/portfolio': typeof PortfolioRoute
  '/whatif': typeof WhatifRoute
  '/workspace': typeof WorkspaceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/comps': typeof CompsRoute
  '/explainability': typeof ExplainabilityRoute
  '/feedback': typeof FeedbackRoute
  '/model': typeof ModelRoute
  '/portfolio': typeof PortfolioRoute
  '/whatif': typeof WhatifRoute
  '/workspace': typeof WorkspaceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/comps': typeof CompsRoute
  '/explainability': typeof ExplainabilityRoute
  '/feedback': typeof FeedbackRoute
  '/model': typeof ModelRoute
  '/portfolio': typeof PortfolioRoute
  '/whatif': typeof WhatifRoute
  '/workspace': typeof WorkspaceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/comps'
    | '/explainability'
    | '/feedback'
    | '/model'
    | '/portfolio'
    | '/whatif'
    | '/workspace'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/comps'
    | '/explainability'
    | '/feedback'
    | '/model'
    | '/portfolio'
    | '/whatif'
    | '/workspace'
  id:
    | '__root__'
    | '/'
    | '/comps'
    | '/explainability'
    | '/feedback'
    | '/model'
    | '/portfolio'
    | '/whatif'
    | '/workspace'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompsRoute: typeof CompsRoute
  ExplainabilityRoute: typeof ExplainabilityRoute
  FeedbackRoute: typeof FeedbackRoute
  ModelRoute: typeof ModelRoute
  PortfolioRoute: typeof PortfolioRoute
  WhatifRoute: typeof WhatifRoute
  WorkspaceRoute: typeof WorkspaceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatif': {
      id: '/whatif'
      path: '/whatif'
      fullPath: '/whatif'
      preLoaderRoute: typeof WhatifRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model': {
      id: '/model'
      path: '/model'
      fullPath: '/model'
      preLoaderRoute: typeof ModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explainability': {
      id: '/explainability'
      path: '/explainability'
      fullPath: '/explainability'
      preLoaderRoute: typeof ExplainabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comps': {
      id: '/comps'
      path: '/comps'
      fullPath: '/comps'
      preLoaderRoute: typeof CompsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompsRoute: CompsRoute,
  ExplainabilityRoute: ExplainabilityRoute,
  FeedbackRoute: FeedbackRoute,
  ModelRoute: ModelRoute,
  PortfolioRoute: PortfolioRoute,
  WhatifRoute: WhatifRoute,
  WorkspaceRoute: WorkspaceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
